### ISSUE TITLE
cargo run failed

### ISSUE THREAD

**Issue by lcgogo** [openethereum/3.1-db-upgrade-tool#1]
Compiling thiserror v1.0.20
   Compiling structopt v0.3.11
   Compiling parity-util-mem v0.5.1
   Compiling kvdb v0.4.0
   Compiling librocksdb-sys v6.6.4
error: failed to run custom build command for `librocksdb-sys v6.6.4`

Caused by:
  process didn't exit successfully: `/root/3.1-db-upgrade-tool/target/debug/build/librocksdb-sys-45234b6378becc24/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.1/src/lib.rs:1956:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by rakita** [comment]
Clang is needed, please install it
