### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by kael-shipman** [openethereum/3.1-db-upgrade-tool#3]
@adria0 I'm running a production Ethereum node at Parity v2.5.13, and I've just updated to OpenEthereum v3.1.0. However, when I try to run it, it tells me to use the db upgrade tool here. I came to this repo and have no idea how to use the tool. Could you please update the readme with more detailed instructions?

**Comment by rakita** [comment]
download repo and run:  `cargo run "~/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent"`
you will need to install rust and clang and thats it.
