### ISSUE TITLE
What's the upgrade path from parity-2.6.8-beta?

### ISSUE THREAD

**Issue by c0deright** [openethereum/3.1-db-upgrade-tool#5]
Hi,

the db upgrade tool specifically only mentions these versions:

> Migrate the openethereum db from 2.5.13, 2.7.2, 3.0.1 to 3.1.0

```
/// Parity 2.5.13 db model version
const PARITY_2_5_13_VERSION: u32 = 13;

/// Parity 2.7.2 db model version
const PARITY_2_7_2_VERSION: u32 = 14;

/// OpenEthereum 3.0.1 db model version
const OE_3_0_1_VERSION: u32 = 15;

/// OpenEthereum 3.1.0 db model version
const OE_3_1_0_VERSION: u32 = 16;
```

I suspect parity v2.6.8-beta's DB to be version 13 and thus being covered by the migration tool.

Is this assumption correct? If yes, you might want to update the README.md to be a bit more precise about the version numbers to reduce confusion. Thanks!

**Comment by rakita** [comment]
Should work, but not sure if there are any additional changes in that particular version. Those versions were never officially released, but they were merged in 2.7.0.
