### ISSUE TITLE
running on ropsten

### ISSUE THREAD

**Issue by bert2002** [openethereum/3.1-db-upgrade-tool#8]
Hi,
I assume this is needed for ropsten as well, but I am running into this problem.

```
~/3.1-db-upgrade-tool$ cargo run "$PARITY_PATH/chains/ropsten/db/ae90623718e47d66/overlayrecent"
   ...
   Compiling librocksdb-sys v6.6.4
   Compiling rocksdb v0.13.0
   Compiling kvdb-rocksdb v0.6.0
   Compiling oe-upgrage-db-3-1 v0.1.0-rc1 (/home/parity/3.1-db-upgrade-tool)
    Finished dev [unoptimized + debuginfo] target(s) in 8m 03s
     Running `target/debug/oe-upgrage-db-3-1 /home/parity/.local/share/io.parity.ethereum/chains/ropsten/db/ae90623718e47d66/overlayrecent`
Error: UnknownDatabaseVersion("cannot open: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }")
```
Is this DB upgrade necessary or will OE do it automatically when starting as well?

Thanks,
bert

**Comment by rakita** [comment]
can you check if the folder path exists?

**Comment by bert2002** [comment]
> can you check if the folder path exists?

The path `/home/parity/.local/share/io.parity.ethereum/chains/ropsten/db/ae90623718e47d66/` exist, but not `/home/parity/.local/share/io.parity.ethereum/chains/ropsten/db/ae90623718e47d66/overlayrecent`. Is it not going to create it?

**Comment by rakita** [comment]
Sorry, a little bit late to respond, just change the path to point to the existing folder

**Comment by bert2002** [comment]
Yeah seems for archive node its `archive` and not `overlayrecent`. Didnt see that in the docs or was added later.
