### ISSUE TITLE
Is it mandatory to run 3.1-db-upgrade-tool for those who uses 3.0.1?

### ISSUE THREAD

**Issue by rlaace423** [openethereum/3.1-db-upgrade-tool#9]
Hi, I'm using v3.0.1 binary for Ropsten.
Now I'm trying to upgrade it to 3.1.0, but I found this repo.

It is necessary? Furthermore, README says that **THIS IS BETA SOFTWARE**, so I'm afraid my ropsten db to be corrupted.
Is there any safer way to upgrade binary from 3.0.1 to 3.1.0? Is this repo is the only way?

Always, thanks!

**Comment by vkconsult** [comment]
I'm also concerned about this.
OpenEthereum [reminds us](https://twitter.com/OpenEthereumOrg/status/1326510282760482819) to update our nodes, but doesn't do anything to make it a feasible option.
I will not risk our production nodes by running this poorly developed beta tool. There does not seem to be any activity concerning this upgrade around here. What's going on?

**Comment by rakita** [comment]
running db-tool is required to upgrade DB to v3.1.0. As you can see in code this is more script than a tool and there are multiple reports that it works even for archive node. But either way it is a good option to make a backup, just in case.
